LivrariaControleEmprestimo.WEB/Models/EmprestimoViewModel.cs
using LivrariaContreleEmprestimo.DATA.Models;

namespace LivrariaControleEmprestimo.WEB.Models
{
    public class EmprestimoViewModel
    {
        public Cliente oCliente { get; set; }
        public Livro oLivro { get; set; }
        public int oClienteId { get; set; }
        public int oLivroId { get; set; }
        public DateTime dataEntrega { get; set; }
        public DateTime dataEmprestimo { get; set; }
        public List<Cliente> oListCliente { get; set; }
        public List<Livro> oListLivro { get; set; }
    }
}

LivrariaControleEmprestimo.WEB/Models/ErrorViewModel.cs
namespace LivrariaControleEmprestimo.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LivrariaControleEmprestimo.WEB/Controllers/ClienteController.cs
using LivrariaContreleEmprestimo.DATA.Models;
using LivrariaContreleEmprestimo.DATA.Services;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class ClienteController : Controller
    {
        private ClienteService oClienteService = new ClienteService();
        public IActionResult Index()
        {
            List<Cliente> oListClientes = oClienteService.oRepositoryCliente.SelecionarTodos();
            return View(oListClientes);
        }
        public IActionResult Create() 
        { 
            return View(); 
        }
        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            oClienteService.oRepositoryCliente.Incluir(cliente);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            Cliente cliente = oClienteService.oRepositoryCliente.SelecionarPk(id);
            return View(cliente);
        }
        public IActionResult Edit(int id)
        {
            Cliente cliente = oClienteService.oRepositoryCliente.SelecionarPk(id);
            return View(cliente);
        }
        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.Alterar(cliente);

            int id = oCliente.Id;

            return RedirectToAction("Details", new { id });
        }
        public IActionResult Delete(int id)
        {
            oClienteService.oRepositoryCliente.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

LivrariaControleEmprestimo.WEB/Controllers/EmprestimoController.cs
using LivrariaContreleEmprestimo.DATA.Models;
using LivrariaContreleEmprestimo.DATA.Services;
using LivrariaControleEmprestimo.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class EmprestimoController : Controller
    {
        private LivroClienteEmprestimoService _emprestimoService = new LivroClienteEmprestimoService();
        private EmprestimoViewModel oEmprestimoViewModel = new EmprestimoViewModel();
        public EmprestimoController(EmprestimoViewModel _EmprestimoViewModel)
        {
            oEmprestimoViewModel = _EmprestimoViewModel;
        }
        
        public IActionResult Index()
        {
            List<VwLivroClienteEmprestimo> oListVwLivroClienteEmprestimos = _emprestimoService.oRepositoryVwLivroClienteEmprestimo.SelecionarTodos();
            return View(oListVwLivroClienteEmprestimos);
        }
        public IActionResult Create()
        {
            EmprestimoViewModel oEmprestimoViewModel = new EmprestimoViewModel();
            List<Cliente> oListCliente = _emprestimoService.oRepositoryCliente.SelecionarTodos();
            List<Livro> oListLivro = _emprestimoService.oRepositoryLivro.SelecionarTodos();

            oEmprestimoViewModel.oListCliente = oListCliente;
            oEmprestimoViewModel.oListLivro = oListLivro;
            oEmprestimoViewModel.dataEmprestimo = DateTime.Now;
            oEmprestimoViewModel.dataEntrega = DateTime.Now.AddDays(7);

            return View(oEmprestimoViewModel);
        }
        [HttpPost]
        public IActionResult Create(EmprestimoViewModel oEmprestimoViewModel)
        {
            LivroClienteEmprestimo oLivroClienteEmprestimo = new LivroClienteEmprestimo();
            oLivroClienteEmprestimo.LceldDataEmprestimo = oEmprestimoViewModel.dataEmprestimo;
            oLivroClienteEmprestimo.LceldDataEntrega = oEmprestimoViewModel.dataEntrega;
            oLivroClienteEmprestimo.LceldLivro = Convert.ToInt32(oEmprestimoViewModel.oLivroId);
            oLivroClienteEmprestimo.LceldCliente = Convert.ToInt32(oEmprestimoViewModel.oClienteId);
            oLivroClienteEmprestimo.LceldEntregue = false;

            if (!ModelState.IsValid)
            {
                return View(oEmprestimoViewModel);
            }

            

            _emprestimoService.oRepositoryLivroClienteEmprestimo.Incluir(oLivroClienteEmprestimo);
            return RedirectToAction("Index");
        }
    }


}

LivrariaControleEmprestimo.WEB/Controllers/HomeController.cs
using LivrariaControleEmprestimo.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LivrariaControleEmprestimo.WEB/Controllers/LivroController.cs
using LivrariaContreleEmprestimo.DATA.Models;
using LivrariaContreleEmprestimo.DATA.Services;
using Microsoft.AspNetCore.Mvc;

namespace LivrariaControleEmprestimo.WEB.Controllers
{
    public class LivroController : Controller
    {
        private LivroService oLivroService = new LivroService();
        public IActionResult Index()
        {
            List<Livro> oListaLivros = oLivroService.oRepositoryLivro.SelecionarTodos();
            return View(oListaLivros);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Livro livro)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            oLivroService.oRepositoryLivro.Incluir(livro);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            Livro livro = oLivroService.oRepositoryLivro.SelecionarPk(id);
            return View(livro);
        }
        public IActionResult Edit(int id)
        {
            Livro livro = oLivroService.oRepositoryLivro.SelecionarPk(id);
            return View(livro);
        }
        [HttpPost]
        public IActionResult Edit(Livro livro)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            Livro oLivro = oLivroService.oRepositoryLivro.Alterar(livro);
            int id = oLivro.Id;

            return RedirectToAction("Details", new { id });
        }
        public IActionResult Delete(int id)
        {
            oLivroService.oRepositoryLivro.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Create.cshtml
@model LivrariaContreleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastro de novos clientes</h1>

<h4>Dados do cliente</h4>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar para a lista</a>
</div>
<br/>
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card">
                <div class="card-header">Informações Pessoais</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliNome" class="control-label"></label>
                            <input asp-for="CliNome" class="form-control" />
                            <span asp-validation-for="CliNome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliCpf" class="control-label"></label>
                            <input asp-for="CliCpf" class="form-control" />
                            <span asp-validation-for="CliCpf" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Endereço</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliEndereco" class="control-label"></label>
                            <input asp-for="CliEndereco" class="form-control" />
                            <span asp-validation-for="CliEndereco" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CliCidade" class="control-label"></label>
                            <input asp-for="CliCidade" class="form-control" />
                            <span asp-validation-for="CliCidade" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliBairro" class="control-label"></label>
                            <input asp-for="CliBairro" class="form-control" />
                            <span asp-validation-for="CliBairro" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CliNumero" class="control-label"></label>
                            <input asp-for="CliNumero" class="form-control" />
                            <span asp-validation-for="CliNumero" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Informações para Contato</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneCelular" class="control-label"></label>
                            <input asp-for="CliTelefoneCelular" class="form-control" />
                            <span asp-validation-for="CliTelefoneCelular" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliEmail" class="control-label"></label>
                            <input asp-for="CliEmail" class="form-control" />
                            <span asp-validation-for="CliEmail" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar Contato" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Details.cshtml
@model LivrariaContreleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes do CLiente</h1>
<h4>Dados do cliente</h4>
<hr />
<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">Editar Cliente</a>
    <a class="btn btn-primary" asp-action="Index">Voltar para a lista</a>
</div>
<br />
<div class="card">
    <div class="card-header">Informações Pessoais</div>
    <div class="card-body row">
        <div class="col-md">
            <div class="form-group">
                <label>@Html.DisplayNameFor(model => model.CliNome)</label>
                <input value="@Html.DisplayFor(model => model.CliNome)" disabled class="form-control" />
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label>@Html.DisplayNameFor(model => model.CliCpf)</label>
                <input value="@Html.DisplayFor(model => model.CliCpf)" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>
<br />
<div class="card">
    <div class="card-header">Endereço</div>
    <div class="card-body row">
        <div class="col-md">
            <label>@Html.DisplayNameFor(model => model.CliEndereco)</label>
            <input value="@Html.DisplayFor(model => model.CliEndereco)" disabled class="form-control" />
            <label>@Html.DisplayNameFor(model => model.CliCidade)</label>
            <input value="@Html.DisplayFor(model => model.CliCidade)" disabled class="form-control" />
        </div>
        <div class="col-md">
            <label>@Html.DisplayNameFor(model => model.CliBairro)</label>
            <input value="@Html.DisplayFor(model => model.CliBairro)" disabled class="form-control" />
            <label>@Html.DisplayNameFor(model => model.CliNumero)</label>
            <input value="@Html.DisplayFor(model => model.CliNumero)" disabled class="form-control" />
        </div>
    </div>
</div>
<br />
<div class="card">
    <div class="card-header">Informações para Contato</div>
    <div class="card-body row">
        <div class="col-md">
            <label>@Html.DisplayNameFor(model => model.CliTelefoneCelular)</label>
            <input value="@Html.DisplayFor(model => model.CliTelefoneCelular)" disabled class="form-control" />
        </div>
        <div class="col-md">
            <label>@Html.DisplayNameFor(model => model.CliEmail)</label>
            <input value="@Html.DisplayFor(model => model.CliEmail)" disabled class="form-control" />
        </div>
    </div>
</div>
<br />

LivrariaControleEmprestimo.WEB/Views/Cliente/Edit.cshtml
@model LivrariaContreleEmprestimo.DATA.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar o cadastro do cliente</h1>


<h4>Dados</h4>
<hr />

<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div hidden class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div>
                <input type="submit" value="Atualizar contato" class="btn btn-success" />
                <a class="btn btn-primary" asp-action="Index">Voltar para a lista</a>
            </div>
            <br/>
            <div class="card">
                <div class="card-header">Informações Pessoais</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliNome" class="control-label"></label>
                            <input asp-for="CliNome" class="form-control" />
                            <span asp-validation-for="CliNome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliCpf" class="control-label"></label>
                            <input asp-for="CliCpf" class="form-control" />
                            <span asp-validation-for="CliCpf" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Endereço</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliEndereco" class="control-label"></label>
                            <input asp-for="CliEndereco" class="form-control" />
                            <span asp-validation-for="CliEndereco" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CliCidade" class="control-label"></label>
                            <input asp-for="CliCidade" class="form-control" />
                            <span asp-validation-for="CliCidade" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliBairro" class="control-label"></label>
                            <input asp-for="CliBairro" class="form-control" />
                            <span asp-validation-for="CliBairro" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CliNumero" class="control-label"></label>
                            <input asp-for="CliNumero" class="form-control" />
                            <span asp-validation-for="CliNumero" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="card">
                <div class="card-header">Informações para Contato</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliTelefoneCelular" class="control-label"></label>
                            <input asp-for="CliTelefoneCelular" class="form-control" />
                            <span asp-validation-for="CliTelefoneCelular" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="CliEmail" class="control-label"></label>
                            <input asp-for="CliEmail" class="form-control" />
                            <span asp-validation-for="CliEmail" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LivrariaControleEmprestimo.WEB/Views/Cliente/Index.cshtml
@model IEnumerable<LivrariaContreleEmprestimo.DATA.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-4">Lista de Clientes </h1>
<br />
<p>
    <a class="btn btn-primary" asp-action="Create">Adicionar novo cliente</a>
</p>
<br/>
<table class="table" id="tabela-clientes">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CliCpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliNome)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.CliCidade)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.CliTelefoneCelular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CliCpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CliNome)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.CliCidade)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.CliTelefoneCelular)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.CliEmail)
            </td>
            
                <td class="btn-group" role="group">
                        <a class="btn btn-warning m-1" asp-action="Edit" asp-route-id="@item.Id">Alterar</a>
                        <a class="btn btn-primary m-1" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                        

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger m-1" data-bs-toggle="modal" data-bs-target="#deleteModal-@item.Id">
                        Excluir
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal-@item.Id" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteModalLabel">Excluir cliente</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.CliNome ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">Não</button>
                                    <a class="btn btn-danger m-1" asp-action="Delete" asp-route-id="@item.Id">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            
        </tr>
}
    </tbody>
</table>

LivrariaControleEmprestimo.WEB/Views/Emprestimo/Index.cshtml
@model IEnumerable<LivrariaContreleEmprestimo.DATA.Models.VwLivroClienteEmprestimo>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Empréstimos</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Realizar novo Empréstimo</a>
</p>
<table class="table" id="tabela-emprestimo">
    <thead>
        <tr>
            <th>
            @Html.DisplayNameFor(model => model.CliCpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CliNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LivroNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceldDataEmprestimo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceldDataEntrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LceldEntregue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CliCpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CliNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LivroNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceldDataEmprestimo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceldDataEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LceldEntregue)
            </td>
            <td>
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

LivrariaControleEmprestimo.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LivrariaControleEmprestimo.WEB/Views/Livro/Create.cshtml
@model LivrariaContreleEmprestimo.DATA.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastro de novos livros</h1>

<h4>Dados do livro</h4>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar para a lista</a>
</div>
<br />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card">
                <div class="card-header">Informações sobre o Livro</div>
                <div class="card-body row">
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="LivroNome" class="control-label"></label>
                            <input asp-for="LivroNome" class="form-control" />
                            <span asp-validation-for="LivroNome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LivroAutor" class="control-label"></label>
                            <input asp-for="LivroAutor" class="form-control" />
                            <span asp-validation-for="LivroAutor" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LivroEditora" class="control-label"></label>
                            <input asp-for="LivroEditora" class="form-control" />
                            <span asp-validation-for="LivroEditora" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-group">
                            <label asp-for="LivroEdicao" class="control-label"></label>
                            <input asp-for="LivroEdicao" class="form-control" />
                            <span asp-validation-for="LivroEdicao" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LivroAnoPublicacao" class="control-label"></label>
                            <input asp-for="LivroAnoPublicacao" class="form-control" />
                            <span asp-validation-for="LivroAnoPublicacao" class="text-danger"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Cadastrar livro " class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LivrariaControleEmprestimo.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/LivrariaControleEmprestimo.WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca.org</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Empréstimo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Catálogo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Biblioteca.org - <a asp-area="" asp-controller="Home" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>